### ISSUE TITLE
There are invalid links to tables in the file betydb_tables.md.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/betydb-documentation#3]
The table references could either be omitted, or the references could link directly to the www.betydb.org site.  For example, what is now called "Table 2" and linked to a missing image inside the GitBook could be renamed to "List of BETY database tables" and linked to either https://www.betydb.org/schemas or https://www.betydb.org/db_docs/index.html.  Similarly for the join tables listed as tables 4, 5, 10, 12, and 13.  The names could be replaced by the actual database name of the table and linked to (taking `citations_sites` as an example) https://www.betydb.org/schemas?partial=citations_sites_table or https://www.betydb.org/db_docs/tables/citations_sites.html.

Note that if link locations are likely to change or if they are going to used on multiple pages, we might want to add a level of indirection by using GitBook variables.  (See the Variables section of the page https://help.gitbook.com/format/templating.html).

**Comment by gsrohde** [comment]
@dlebauer Did you copy the content of this file (along with all the table references) from somewhere else?

**Comment by dlebauer** [comment]
I tried to edit this in the new version of gitbook a few weeks ago. Table 2 refers to the table 2 in the same page (betydb_tables.md), and can be seen here: https://github.com/PecanProject/betydb-documentation/blob/master/betydb_tables.md#table-2-list-of-key-data-tables-in-betydb

I don't see any other links on this version of the page: https://github.com/PecanProject/betydb-documentation/blob/master/betydb_tables.md, but it would make sense to link to the pages in betydb.org/schemas as you suggest.

But regarding your comment 
> we might want to add a level of indirection by using GitBook variables.

Aren't we migrating this to using bookdown?

**Comment by gsrohde** [comment]
> I tried to edit this in the new version of gitbook a few weeks ago. Table 2 refers to the table 2 in the same page (betydb_tables.md), and can be seen here: https://github.com/PecanProject/betydb-documentation/blob/master/betydb_tables.md#table-2-list-of-key-data-tables-in-betydb
> 

Yes, I saw Table 2, just not any of the other tables.

> I don't see any other links on this version of the page: https://github.com/PecanProject/betydb-documentation/blob/master/betydb_tables.md, but it would make sense to link to the pages in betydb.org/schemas as you suggest.

I thought maybe this page was copied from a version of the documentation (maybe in whatever we used before GitBook) and that somehow the referred-to tables didn't make the migration.  If not, I'll either link to the schema doc or remove these table references.

> 
> But regarding your comment
> 
> > we might want to add a level of indirection by using GitBook variables.
> 
> Aren't we migrating this to using bookdown? never mind I see this comment was from 2016!

**Comment by gsrohde** [comment]
Spurious table references were removed.  Closing.
